{
    "1. Что делает finally? Когда он выполняется?": "finally — выполняется всегда, даже если в блоке try произошла ошибка.",
    "2. Можно ли написать try без except?": " возможно, но не рекомендуется, так как ошибки не будут обработаны",
    "3. Чем Exception отличается от конкретных ошибок (ValueError, ZeroDivisionError)?": "`Exception` — это базовый класс для всех исключений в Python. базовый класс для всех исключений, тогда как ValueError и ZeroDivisionError — конкретные типы ошибок",
    "4. Можно ли использовать несколько except в одном try?": "Да, в одном блоке `try` можно использовать несколько блоков `except`, чтобы обрабатывать разные типы ошибок по-разному.",
    "5. Что произойдет, если в except не указать тип ошибки?": "Если в `except` не указать тип ошибки, то этот блок будет перехватывать все исключения. Это может затруднить отладку, так как вы не будете знать, какая именно ошибка произошла."
}